export const styles = {
  app: { 
    display: 'flex',
    flexDirection: 'column',
    minHeight: '100vh',
    fontFamily: 'system-ui, sans-serif',
    background: '#0D0D0D',
    color: '#E5E5E5',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '18px 24px',
    background: '#0D0D0D',
    borderBottom: '1px solid #2A2A2A',
    position: 'sticky',
    top: 0,
    zIndex: 20,
  },
  headerTitle: {
    marginLeft: '12px',
    margin: 0,
    fontSize: '1.35rem',
    letterSpacing: '-0.04em',
    color: '#A855F7',
  },
  headerNav: {
    marginRight: '12px',
    display: 'flex',
    gap: '12px',
    flexWrap: 'wrap',
  },
  pageButton: {
    padding: '10px 16px',
    fontSize: '0.95rem',
    borderRadius: '10px',
    border: '1px solid #2A2A2A',
    background: '#1A1A1A',
    color: '#E5E5E5',
    cursor: 'pointer',
    outline: 'none',
  },
  pageButtonActive: {
    background: '#A855F7',
    color: '#0D0D0D',
    border: '1px solid #2A2A2A',
    outline: 'none',
  },
  pageMain: {
    display: 'flex',
    justifyContent: 'center',
    flex: 0.5,
    width: '100%',
    padding: '24px 18px 100px',
    boxSizing: 'border-box',
  },
  sectionTitle: {
    margin: '0 0 14px',
    fontSize: '1.35rem',
    color: '#E5E5E5', 
    textAlign: 'left',
  },
  menu: {
    padding: '30px',
    background: '#1A1A1A',
    border: '1px solid #2A2A2A',
    borderRadius: '20px',
  },
    menuGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(170px, 1fr))',
    gap: '12px',
  },
  botao: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '14px 16px',
    borderRadius: '15px',
    border: '1px solid #2A2A2A',
    background: '#1A1A1A',
    color: '#E5E5E5',
    cursor: 'pointer',
    textAlign: 'left',
    fontSize: '0.95rem',
    transition: 'transform 0.15s ease, border-color 0.15s ease, background 0.15s ease',
  },
  botaoActive: {
    background: '#A855F7',
    color: '#0D0D0D',
    transform: 'translateY(-1px)',
  },
  avatarImg: {
    width: '48px',
    height: '48px',
    borderRadius: '50%',
    objectFit: 'cover',
  },
  card: {
    padding: '22px',
    background: '#1A1A1A',
    border: '1px solid #2A2A2A',
    borderRadius: '20px',
    boxShadow: '0 18px 40px rgba(0, 0, 0, 0.35)',
  },
  cardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '18px',
    flexWrap: 'wrap',
    gap: '12px',
  },
  cardTitle: {
    margin: 0,
    fontSize: '1.35rem',
  },
  cardList: {
    listStyle: 'none',
    padding: 0,
    margin: 0,
    display: 'grid',
    gap: '14px',
  },
  cardItem: {
    padding: '16px',
    borderRadius: '14px',
    border: '1px solid #2A2A2A',
    background: '#0D0D0D',
    textAlign: 'left',
  },
  cardItemLabel: {
    margin: 0,
    fontSize: '1rem',
    fontWeight: '700',
    color: '#E5E5E5',
  },
  cardItemText: {
    margin: '8px 0 0',
    lineHeight: '1.6',
    color: '#A1A1AA',
    whiteSpace: 'pre-wrap',
  },
  content: {
    padding: '22px',
    background: '#1A1A1A',
    border: '1px solid #2A2A2A',
    borderRadius: '20px',
    justifyContent: 'center',
    boxSizing: 'border-box',
    textAlign: 'left',
  },
  teamList: {
    listStyle: 'none',
    padding: 0,
    margin: 0,
    display: 'grid',
    gap: '12px',
  },
  teamItem: {
    padding: '16px',
    borderRadius: '14px',
    border: '1px solid #2A2A2A',
    background: '#1A1A1A',
    color: '#E5E5E5',
  },
  footer: {
    padding: '18px 20px',
    background: '#0D0D0D',
    borderTop: '1px solid #2A2A2A',
    textAlign: 'center',
    position: 'fixed',
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 10,
  },
  footerLink: {
    display: 'inline-block',
    marginBottom: '10px',
    color: '#A855F7',
    textDecoration: 'none',
    fontWeight: '700',
  },
  footerText: {
    margin: 0,
    color: '#E5E5E5',
    fontSize: '0.96rem',
  },
};
